### ISSUE TITLE
real time ?

### ISSUE THREAD

**Issue by gao123qiang** [vladmandic/human-pose#1]
wh is your gpu?
the fps in your gpu ?

**Comment by vladmandic** [comment]
this is not intended for real time as output is not video, but `json` file that can be later used by client demo app or any other visualization app. 

and performance highly depends on 
- which model (tiny/small/large/large360)
- input resolution
- number of people in the scene (each detected person is analyzed separately)
- other processing parameters

given all that, performance can vary from 0.05sec/frame to 5sec/frame

**Comment by gao123qiang** [comment]
current: mov --> model --> keypoints --> 3d.json --> 3D Visualization.
if not 3D Visualization, only return the keypoints,  mov:1080p + two people, how many is the fps about ?
20fps/s ?

**Comment by vladmandic** [comment]
with `tiny` model on rtx3080 and using default parameters it will get close to 20fps, with `small` or `large`, not really as they are far more compute intensive
